import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { FileDown, FileText, PieChart, ShieldAlert, Users } from "lucide-react";
import jsPDF from "jspdf";

interface AdminReportsProps {
    stats: any;
    providers: any[];
    patients: any[];
    facilities: any[];
    referrals: any[];
}

const AdminReports = ({ stats, providers, patients, facilities, referrals }: AdminReportsProps) => {
    const [generating, setGenerating] = useState(false);

    // Calculate dynamic stats
    const userStats = {
        total: (patients?.length || 0) + (providers?.length || 0),
        active: (patients?.filter(p => p.status === 'active').length || 0) + (providers?.filter(p => p.status === 'active').length || 0),
        suspended: (patients?.filter(p => p.status === 'suspended').length || 0) + (providers?.filter(p => p.status === 'suspended').length || 0),
        pending: stats?.pendingUsers || 0
    };

    const providerStats = {
        total: providers?.length || 0,
        doctors: providers?.filter(p => p.role === 'doctor').length || 0,
        nurses: providers?.filter(p => p.role === 'nurse').length || 0,
        others: providers?.filter(p => !['doctor', 'nurse'].includes(p.role)).length || 0
    };

    const facilityStats = {
        total: facilities?.length || 0,
        active: facilities?.filter(f => f.status === 'active').length || 0,
        levels: facilities?.reduce((acc: any, curr: any) => {
            const level = curr.facility_levels?.level || 'Unknown';
            acc[level] = (acc[level] || 0) + 1;
            return acc;
        }, {})
    };

    const referralStats = {
        total: referrals?.length || 0,
        completed: referrals?.filter(r => r.status === 'completed').length || 0,
        pending: referrals?.filter(r => r.status === 'pending').length || 0,
        inProgress: referrals?.filter(r => ['in_progress', 'accepted', 'reviewed'].includes(r.status)).length || 0
    };

    const generatePDF = () => {
        setGenerating(true);
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const today = new Date().toLocaleDateString();

        // Helper for centered text
        const centerText = (text: string, y: number, size = 12) => {
            doc.setFontSize(size);
            const textWidth = doc.getStringUnitWidth(text) * size / doc.internal.scaleFactor;
            const x = (pageWidth - textWidth) / 2;
            doc.text(text, x, y);
        };

        // --- Header ---
        centerText("AfyaLink Secure Referral", 20, 18);
        centerText("Comprehensive System Report", 28, 14);
        doc.setFontSize(10);
        doc.text(`Generated on: ${today}`, 20, 35);
        doc.text(`Generated by: Admin User`, 20, 40);
        doc.line(20, 45, pageWidth - 20, 45);

        let yPos = 55;

        // --- 1. User Statistics ---
        doc.setFontSize(14);
        doc.setTextColor(0, 51, 102); // Dark blue
        doc.text("1. User Statistics", 20, yPos);
        yPos += 10;
        doc.setTextColor(0, 0, 0); // Reset color
        doc.setFontSize(11);

        const pdfUserStats = [
            { label: "Total Registered Users", value: userStats.total.toString() },
            { label: "Active Users", value: userStats.active.toString() },
            { label: "Pending Approvals", value: userStats.pending.toString() },
            { label: "Suspended/Deactivated", value: userStats.suspended.toString() },
        ];

        pdfUserStats.forEach(stat => {
            doc.text(`${stat.label}:`, 30, yPos);
            doc.text(`${stat.value}`, 120, yPos);
            yPos += 8;
        });

        yPos += 5;

        // --- 2. Provider Overview ---
        doc.setFontSize(14);
        doc.setTextColor(0, 51, 102);
        doc.text("2. Provider Overview", 20, yPos);
        yPos += 10;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);

        const pdfProviderStats = [
            { label: "Total Registered Providers", value: providerStats.total.toString() },
            { label: "Doctors", value: providerStats.doctors.toString() },
            { label: "Nurses", value: providerStats.nurses.toString() },
            { label: "Other Staff", value: providerStats.others.toString() },
        ];

        pdfProviderStats.forEach(stat => {
            doc.text(`${stat.label}:`, 30, yPos);
            doc.text(`${stat.value}`, 120, yPos);
            yPos += 8;
        });

        yPos += 10;

        // --- 3. Facility Overview ---
        doc.setFontSize(14);
        doc.setTextColor(0, 51, 102);
        doc.text("3. Facility Overview", 20, yPos);
        yPos += 10;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);

        const pdfFacilityStats = [
            { label: "Total Facilities", value: facilityStats.total.toString() },
            { label: "Active Facilities", value: facilityStats.active.toString() },
        ];

        pdfFacilityStats.forEach(stat => {
            doc.text(`${stat.label}:`, 30, yPos);
            doc.text(`${stat.value}`, 120, yPos);
            yPos += 8;
        });

        yPos += 10;

        // --- 4. Referral Statistics ---
        doc.setFontSize(14);
        doc.setTextColor(0, 51, 102);
        doc.text("4. Referral Statistics", 20, yPos);
        yPos += 10;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);

        const pdfReferralStats = [
            { label: "Total Referrals", value: referralStats.total.toString() },
            { label: "Completed", value: referralStats.completed.toString() },
            { label: "In Progress", value: referralStats.inProgress.toString() },
            { label: "Pending", value: referralStats.pending.toString() },
        ];

        pdfReferralStats.forEach(stat => {
            doc.text(`${stat.label}:`, 30, yPos);
            doc.text(`${stat.value}`, 120, yPos);
            yPos += 8;
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Confidential Report - For Internal Use Only", 20, 280);
        doc.text(`Page 1 of 1`, pageWidth - 40, 280);

        doc.save(`AfyaLink_Admin_Report_${new Date().toISOString().split('T')[0]}.pdf`);
        setGenerating(false);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold tracking-tight">System Reports</h2>
                <Button onClick={generatePDF} disabled={generating}>
                    {generating ? (
                        <>Generating...</>
                    ) : (
                        <>
                            <FileDown className="mr-2 h-4 w-4" />
                            Download Comprehensive Report
                        </>
                    )}
                </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            User Statistics
                        </CardTitle>
                        <Users className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{userStats.total}</div>
                        <p className="text-xs text-muted-foreground">
                            Total Registered Users
                        </p>
                        <div className="mt-4 text-sm space-y-2">
                            <div className="flex justify-between">
                                <span>Active Users</span>
                                <span className="font-semibold">{userStats.active}</span>
                            </div>
                            <div className="flex justify-between text-warning">
                                <span>Pending Approval</span>
                                <span>{userStats.pending}</span>
                            </div>
                            <div className="flex justify-between text-destructive">
                                <span>Suspended/Deactivated</span>
                                <span>{userStats.suspended}</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Facility Overview
                        </CardTitle>
                        <ShieldAlert className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold text-success">{facilityStats.active}</div>
                        <p className="text-xs text-muted-foreground">
                            Active Facilities
                        </p>
                        <div className="mt-4 text-sm space-y-2">
                            <div className="flex justify-between">
                                <span>Total Facilities</span>
                                <span className="font-semibold">{facilityStats.total}</span>
                            </div>
                            {/* Simple inline display of levels if few, or just summary */}
                            <div className="flex justify-between text-muted-foreground">
                                <span>Level 6 Hospitals</span>
                                <span>{facilityStats.levels['6'] || 0}</span>
                            </div>
                            <div className="flex justify-between text-muted-foreground">
                                <span>Level 4-5 Hospitals</span>
                                <span>{(facilityStats.levels['4'] || 0) + (facilityStats.levels['5'] || 0)}</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Referral Statistics
                        </CardTitle>
                        <FileText className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{referralStats.total}</div>
                        <p className="text-xs text-muted-foreground">
                            Total Referrals
                        </p>
                        <div className="mt-4 text-sm space-y-2">
                            <div className="flex justify-between">
                                <span>Completed</span>
                                <span className="font-semibold text-success">{referralStats.completed}</span>
                            </div>
                            <div className="flex justify-between text-primary">
                                <span>In Progress</span>
                                <span>{referralStats.inProgress}</span>
                            </div>
                             <div className="flex justify-between text-warning">
                                <span>Pending</span>
                                <span>{referralStats.pending}</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Provider Breakdown
                        </CardTitle>
                        <PieChart className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{providerStats.total}</div>
                        <p className="text-xs text-muted-foreground">
                            Registered Providers
                        </p>
                        <div className="mt-4 text-sm space-y-2">
                            <div className="flex justify-between">
                                <span>Doctors</span>
                                <span className="font-semibold">{providerStats.doctors}</span>
                            </div>
                            <div className="flex justify-between">
                                <span>Nurses</span>
                                <span>{providerStats.nurses}</span>
                            </div>
                            <div className="flex justify-between">
                                <span>Others</span>
                                <span>{providerStats.others}</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <div className="rounded-md border p-4 bg-muted/20">
                <p className="text-sm text-center text-muted-foreground">
                    Click "Download Comprehensive Report" to generate a detailed PDF containing all these metrics and more.
                </p>
            </div>
        </div>
    );
};

export default AdminReports;
