import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { FileDown, FileText, PieChart, ShieldAlert, Users } from "lucide-react";
import jsPDF from "jspdf";

const AdminReports = () => {
    const [generating, setGenerating] = useState(false);

    const generatePDF = () => {
        setGenerating(true);
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const today = new Date().toLocaleDateString();

        // Helper for centered text
        const centerText = (text: string, y: number, size = 12) => {
            doc.setFontSize(size);
            const textWidth = doc.getStringUnitWidth(text) * size / doc.internal.scaleFactor;
            const x = (pageWidth - textWidth) / 2;
            doc.text(text, x, y);
        };

        // --- Header ---
        centerText("AfyaLink Secure Referral", 20, 18);
        centerText("Comprehensive System Report", 28, 14);
        doc.setFontSize(10);
        doc.text(`Generated on: ${today}`, 20, 35);
        doc.text(`Generated by: Admin User`, 20, 40);
        doc.line(20, 45, pageWidth - 20, 45);

        let yPos = 55;

        // --- 1. User Statistics ---
        doc.setFontSize(14);
        doc.setTextColor(0, 51, 102); // Dark blue
        doc.text("1. User Statistics", 20, yPos);
        yPos += 10;
        doc.setTextColor(0, 0, 0); // Reset color
        doc.setFontSize(11);

        const userStats = [
            { label: "Total Registered Users", value: "1,245" },
            { label: "Active Users (Last 30 days)", value: "892" },
            { label: "Inactive Users", value: "353" },
            { label: "Suspended/Deactivated", value: "8" },
        ];

        userStats.forEach(stat => {
            doc.text(`${stat.label}:`, 30, yPos);
            doc.text(`${stat.value}`, 120, yPos);
            yPos += 8;
        });

        yPos += 5;

        // --- 2. Provider Overview ---
        doc.setFontSize(14);
        doc.setTextColor(0, 51, 102);
        doc.text("2. Provider Overview", 20, yPos);
        yPos += 10;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);

        const providerStats = [
            { label: "Total Registered Providers", value: "148" },
            { label: "Doctors", value: "89" },
            { label: "Nurses", value: "42" },
            { label: "Pharmacists", value: "12" },
            { label: "Lab Technicians", value: "5" },
        ];

        providerStats.forEach(stat => {
            doc.text(`${stat.label}:`, 30, yPos);
            doc.text(`${stat.value}`, 120, yPos);
            yPos += 8;
        });

        // Specialty Breakdown (Mini table)
        yPos += 5;
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text("Active Providers by Specialty:", 30, yPos);
        yPos += 6;
        doc.setFont("helvetica", "normal");

        const specialties = ["Cardiology: 14", "Pediatrics: 18", "Neurology: 8", "Orthopedics: 12", "General Practice: 37"];
        specialties.forEach(spec => {
            doc.text(`- ${spec}`, 35, yPos);
            yPos += 5;
        });

        yPos += 10;

        // --- 3. System & Security ---
        doc.setFontSize(14);
        doc.setTextColor(0, 51, 102);
        doc.text("3. System & Security", 20, yPos);
        yPos += 10;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);

        const securityStats = [
            { label: "Daily Active Users (DAU)", value: "124" },
            { label: "Monthly Active Users (MAU)", value: "892" },
            { label: "Successful Logins (Tooay)", value: "342" },
            { label: "Failed Login Attempts", value: "12" },
            { label: "Security Incidents", value: "0" },
            { label: "System Uptime", value: "99.98%" },
            { label: "Error Rate", value: "0.02%" },
        ];

        securityStats.forEach(stat => {
            doc.text(`${stat.label}:`, 30, yPos);
            doc.text(`${stat.value}`, 120, yPos);
            yPos += 8;
        });

        yPos += 10;

        // --- 4. Support & Feedback ---
        doc.setFontSize(14);
        doc.setTextColor(0, 51, 102);
        doc.text("4. Support & Feedback", 20, yPos);
        yPos += 10;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);

        const supportStats = [
            { label: "Total Support Tickets (This Month)", value: "45" },
            { label: "Resolved Tickets", value: "42" },
            { label: "Pending Tickets", value: "3" },
            { label: "Avg Resolution Time", value: "4.2 hours" },
        ];

        supportStats.forEach(stat => {
            doc.text(`${stat.label}:`, 30, yPos);
            doc.text(`${stat.value}`, 120, yPos);
            yPos += 8;
        });

        yPos += 5;
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text("Common Complaint Categories:", 30, yPos);
        yPos += 6;
        doc.setFont("helvetica", "normal");

        const complaints = ["Login Issues (40%)", "Report Generation (20%)", "Notification Delays (15%)", "Other (25%)"];
        complaints.forEach(comp => {
            doc.text(`- ${comp}`, 35, yPos);
            yPos += 5;
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Confidential Report - For Internal Use Only", 20, 280);
        doc.text(`Page 1 of 1`, pageWidth - 40, 280);

        doc.save(`AfyaLink_Admin_Report_${new Date().toISOString().split('T')[0]}.pdf`);
        setGenerating(false);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold tracking-tight">System Reports</h2>
                <Button onClick={generatePDF} disabled={generating}>
                    {generating ? (
                        <>Generating...</>
                    ) : (
                        <>
                            <FileDown className="mr-2 h-4 w-4" />
                            Download Comprehensive Report
                        </>
                    )}
                </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            User Statistics
                        </CardTitle>
                        <Users className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">1,245</div>
                        <p className="text-xs text-muted-foreground">
                            +180 from last month
                        </p>
                        <div className="mt-4 text-sm space-y-2">
                            <div className="flex justify-between">
                                <span>Active Users</span>
                                <span className="font-semibold">892</span>
                            </div>
                            <div className="flex justify-between text-muted-foreground">
                                <span>Inactive Users</span>
                                <span>353</span>
                            </div>
                            <div className="flex justify-between text-destructive">
                                <span>Suspended</span>
                                <span>8</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Security Overview
                        </CardTitle>
                        <ShieldAlert className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold text-success">99.98%</div>
                        <p className="text-xs text-muted-foreground">
                            System Uptime
                        </p>
                        <div className="mt-4 text-sm space-y-2">
                            <div className="flex justify-between">
                                <span>Successful Logins</span>
                                <span className="font-semibold text-success">342</span>
                            </div>
                            <div className="flex justify-between text-warning">
                                <span>Failed Attempts</span>
                                <span>12</span>
                            </div>
                            <div className="flex justify-between text-muted-foreground">
                                <span>Security Incidents</span>
                                <span>0</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Support Tickets
                        </CardTitle>
                        <FileText className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">45</div>
                        <p className="text-xs text-muted-foreground">
                            Total tickets this month
                        </p>
                        <div className="mt-4 text-sm space-y-2">
                            <div className="flex justify-between">
                                <span>Resolved</span>
                                <span className="font-semibold text-success">42</span>
                            </div>
                            <div className="flex justify-between text-warning">
                                <span>Pending</span>
                                <span>3</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Provider Breakdown
                        </CardTitle>
                        <PieChart className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">148</div>
                        <p className="text-xs text-muted-foreground">
                            Registered Providers
                        </p>
                        <div className="mt-4 text-sm space-y-2">
                            <div className="flex justify-between">
                                <span>Doctors</span>
                                <span className="font-semibold">89</span>
                            </div>
                            <div className="flex justify-between">
                                <span>Nurses</span>
                                <span>42</span>
                            </div>
                            <div className="flex justify-between">
                                <span>Others</span>
                                <span>17</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <div className="rounded-md border p-4 bg-muted/20">
                <p className="text-sm text-center text-muted-foreground">
                    Click "Download Comprehensive Report" to generate a detailed PDF containing all these metrics and more.
                </p>
            </div>
        </div>
    );
};

export default AdminReports;
